
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://theclue.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /bashebiscotti

# Google tracking id

google-tracking-id: "UA-1228370-19"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "it"
author: "Gabriele Baldassarre"
title: "{ Bash e biscotti }"
description: "Blog personale di Gabriele Baldassarre e i suoi esperimenti quotidiani con le più diverse tecnologie."
keywords: "gabriele baldassarre, tecnologia, informatica, tutorial, raspberry, linux, apple"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/logo-nav.png"

background-img: "../img/intro-bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Mi piace l'odore delle GPU che friggono al mattino"
  - text: "Se non puoi jailbreakarlo, non comprarlo"
  - text: "Non c'è nessun problema che un cluster di sei Raspberry Pi non possa risolvere. Con calma."
  - text: "Se hai i soldi, usa OSX. Se non li hai, fatti un hackintosh"
  - text: "Ogni notte, R e biscotti!"
  - text: "Quando tutto il resto fallisce, impila altri livelli alla rete"

me-img: "/img/terradimezzo.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/theclue.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: True
pinterest-share: True
pocket-share: False
vkontakte-share: False

disqus-shortname:

syntax-highlight: True

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Gabriele Baldassarre è uno a cui piace sperimentare affinché le nuove tecnologie lo aiutino a risolvere i problemi. Ciò gli comporta grande soddisfazione. Nulla, tuttavia, in confronto a quando, nel farlo, ti accorgi di un nuovo problema che nemmeno credevi di avere!"
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/theclue"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/gabrielebaldassarre"
  - title: "twitter"
    url: "https://twitter.com/cerealping"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/errore404.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  A cosa serve questo spazio: 'about'
  Social Network Analysis: 'sna'
  Blog: 'latest-post'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
